import keys
#NTP SERVER CONFIG
NTP_SERVER = "87.44.18.206" #"87.44.18.206"  TSSG Carelink NTP server # Alternative: "0.europe.pool.ntp.org"
#MQTT CONFIG
MQTT_DEVICE_ID = keys.DEVICE_ID
MQTT_SERVER = "87.44.18.29" #"87.44.18.29" #"mqtt.staging.carelink.tssg.org"
MQTT_USER_ID = keys.MQTT_USER_ID
MQTT_PWD = keys.MQTT_PWD
#MQTT Topics
MQTT_PUB_STATUS = MQTT_DEVICE_ID + "/status"
MQTT_PUB_STATUS_WIFIAPS = MQTT_DEVICE_ID + "/statusWifiAPs"
MQTT_SUB_ACTIVE = MQTT_DEVICE_ID + "/active"
MQTT_SUB_CONF_ENERGY = MQTT_DEVICE_ID + "/configuration/energyProfile"
MQTT_SUB_CONF_WIFI = MQTT_DEVICE_ID + "/configuration/wifi"
#MQTT PUB SR
MQTT_PUB_SR = 30
#WLAN CONFIG
SSID = keys.SSID
WLANPWD = keys.WLANPWD
#LTE-NB CONFIG
LTENB_APN = keys.LTENB_APN
#LORA CONFIG
APP_EUI = keys.APP_EUI
DEV_EUI = keys.DEV_EUI
APP_KEY = keys.APP_KEY
#ENERGY PROFILE CONFIG
GNSS_SR = 10
LTENB_SR = 30
WIFI_SR = 30
LORA_SR = 30
DEEP_SLEEP = 10000 # 2 hours = 7200000